### ISSUE TITLE
Cartographie avec R

### ISSUE THREAD

**Issue by MarcPozzo** [sylvaindurand/sylvaindurand.org#10]
Bonjour, 

Merci beaucoup pour ce tuto.

Je suis bloqué dès le début pour charger les données.
quand j'utilise la fonction : readOGR
Exemple : departements <- readOGR(dsn="shp/geofla",  layer="DEPARTEMENT")

R me répond : Error in readOGR(dsn = "data", layer = "nuts3", verbose = TRUE) : 
  could not find function "readOGR"

J'ai bien sûr chargé les 3 packages.

Pourriez-vous m'indiquer comment résoudre mon problème svp ?

Merci d'avance.

**Comment by sylvaindurand** [comment]
Hélas, le code est assez ancien (2012, relu la dernière fois en 2014), et je n'ai guère fait de *R* depuis, donc il me sera difficile de vous aider... (sauf à ce qu'une bonne âme passe dans le coin).
