### ISSUE TITLE
Making Jekyll multilingual

### ISSUE THREAD

**Issue by inavarrorubio** [sylvaindurand/sylvaindurand.org#11]
Have you figured out a way to paginate same-language articles?

**Comment by sylvaindurand** [comment]
Unfortunately, I never used pagination so I've no idea how it works on Jekyll. It seems however than several people had trouble to make it works. Couldn't tell you more!

**Comment by vinyanalista** [comment]
I'm also searching for it...

**Comment by vinyanalista** [comment]
I've built a multilingual Jekyll website based on your how to:

- Website: https://kamarada.github.io/
- Source: https://github.com/kamarada/kamarada-website (Jekyll) and https://github.com/kamarada/kamarada.github.io (compiled HTML)

Thank you for your great article! But, as you can see, the website is getting big (mainly the Brazilian Portuguese version) and I need a way to paginate posts.

If I find or develop anything, I'll share it with you.

**Comment by vinyanalista** [comment]
I made it work! Please see that commit. I used the [jekyll-paginate-v2](https://github.com/sverrirs/jekyll-paginate-v2) plugin and filtered pages using locales.

Instructions on how to setup that plugin are here:

https://github.com/sverrirs/jekyll-paginate-v2/blob/master/README-GENERATOR.md

In the future, I'm going to replace @sylvaindurand's `lang` with jekyll-paginate-v2's `locale`, so I don't use two front matter variables with the same purpose.

Hope it helps!

**Comment by vinyanalista** [comment]
Please note that my website is not compatible with GitHub Pages, that's why I have separate repos for Jekyll source and compiled (and served) HTML.

**Comment by vinyanalista** [comment]
The jekyll-paginate-v2 plugin is not supported by GitHub Pages: https://pages.github.com/versions/

**Comment by georgeglessner** [comment]
@vinyanalista I was able to get pagination to work with GitHub Pages by following this issue https://github.com/jekyll/minima/issues/159
