### ISSUE TITLE
Making Jekyll multilingual

### ISSUE THREAD

**Issue by lsolesen** [sylvaindurand/sylvaindurand.org#12]
Are you still using this approach? I can see that your language switcher does also change domain?

**Comment by sylvaindurand** [comment]
Yeah, I use exactly the same! I just added a variable to tell which domain should be used in the link, but both works the same ;)

**Comment by lsolesen** [comment]
Your repo does not contain a _config.yml. What kind of wizardry do you do
to create the site?

**Comment by sylvaindurand** [comment]
I only push the _posts/ folder here, because people tends to fork the entire website, then to put it online; it made Google confuse…
