### ISSUE TITLE
Invalid RSS feed

### ISSUE THREAD

**Issue by robinmetral** [sylvaindurand/sylvaindurand.org#13]
Quick note to let you know that your rss feed seems to be invalid: (I couldn't subscribe to it)

https://validator.w3.org/feed/check.cgi?url=https%3A%2F%2Fwww.sylvaindurand.fr%2Frss.xml

**Comment by sylvaindurand** [comment]
Oops, thank you very much! 
It should be fixed now!

**Comment by robinmetral** [comment]
Confirmed on my end :slightly_smiling_face: 

Take care !
