### ISSUE TITLE
Setting up a Nginx web server on macOS

### ISSUE THREAD

**Issue by RobertEleveld** [sylvaindurand/sylvaindurand.org#14]
I've got problems with installing dependencies for php@7.2:

==> Installing php@7.2 dependency: nghttp2
==> Downloading https://github.com/nghttp2/nghttp2/releases/download/v1.37.0/ngh
==> Downloading from https://github-production-release-asset-2e65be.s3.amazonaws
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/nghttp2/1.37.0 --disable-silent-rules
==> make
Last 15 lines from /Users/robert/Library/Logs/Homebrew/nghttp2/02.make:
    _LIBCPP_INLINE_VISIBILITY unique_ptr(unique_ptr&& __u) _NOEXCEPT
                              ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2613:9: note: candidate constructor [with _Up = shrpx::Http2DownstreamConnection, _Ep = std::__1::default_delete<shrpx::Http2DownstreamConnection>] not viable: no known conversion from 'std::__1::unique_ptr<shrpx::Http2DownstreamConnection, std::__1::default_delete<shrpx::Http2DownstreamConnection> >' to 'unique_ptr<shrpx::Http2DownstreamConnection, std::__1::default_delete<shrpx::Http2DownstreamConnection> > &&' for 1st argument
        unique_ptr(unique_ptr<_Up, _Ep>&& __u,
        ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../include/c++/v1/memory:2628:35: note: candidate template ignored: could not match 'auto_ptr' against 'unique_ptr'
        _LIBCPP_INLINE_VISIBILITY unique_ptr(auto_ptr<_Up>&& __p,
                                  ^
1 error generated.
make[3]: *** [libnghttpx_a-shrpx_client_handler.o] Error 1
make[3]: *** Waiting for unfinished jobs....
mv -f .deps/libnghttpx_a-shrpx_config.Tpo .deps/libnghttpx_a-shrpx_config.Po
make[2]: *** [all-recursive] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

Do not report this issue to Homebrew/brew or Homebrew/core!

Error: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this old version.

Please can you help me to solve this problem for me?

I would like to install a learning management system after this. I'm not a programmer. I'm a user. But I would like to try to learn.

Thanks in advanced.

Robert Eleveld

**Comment by sylvaindurand** [comment]
Hi! I didn't encounter this error, but I guess the answer is in the error message:

```
Error: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this old version.
```
