### ISSUE TITLE
Launch Chromium in kiosk mode

### ISSUE THREAD

**Issue by zeesh1979** [sylvaindurand/sylvaindurand.org#15]
Hi,
I followed ypur tutorial just now and there was one thing missing: for this monitor, u need to connect USB cable as well to make touch working.
Now i need your help. I am using this screen as vertical. for this i added display_rotate=3 and it worked. but the touchscreen oritentation is not and the pointer is behaving like old orientation. how to fix this? also the desktop is not covering full screen due to which the there is difference between the point where i click and where the pointer actually clikcks.....plz help

**Comment by sylvaindurand** [comment]
Unfortunately, I don't use any touchscreen, so I won't be able to help!

**Comment by zeesh1979** [comment]
ok no issues. lets forget about touch. the mouse pointer is also behaving like old orientation. is there any way to fix this? display_rotate is just rotating display or adjusting other parameters as well?

**Comment by sylvaindurand** [comment]
I'm sorry, as I didn't have this situation, I didn't try it.
