### ISSUE TITLE
Color contrasts for article side notes

### ISSUE THREAD

**Issue by robinmetral** [sylvaindurand/sylvaindurand.org#2]
I really like the way you're displaying notes on the side of your content (your `<span class="mar">`)

The only thing is that I find them hard to read because of the low color contrast between text (`#cbcbcb`) and background (`#f3f3f3`) - I hadn't even seen them at first.

I ran the colors in [WebAIM's color contrast checker](https://webaim.org/resources/contrastchecker/?fcolor=CBCBCB&bcolor=F3F3F3) and they are pretty far from passing WCAG guidelines.

You might want to consider changing your text color to `#6f6f6f`(the lightest possible without darkening your background color) to pass the WCAG AA guidelines. Here's [the contrast checker again](https://webaim.org/resources/contrastchecker/?fcolor=6F6F6F&bcolor=F3F3F3).

**Comment by sylvaindurand** [comment]
Hi! Thank you very much for your review and your research!

You are quite right, the color was really too bright for the background. However, I tried `#6f6f6f` and found it really too dark for my taste :( I just put `#999999` right now, how do you feel about it? (I know it's not WCAG AA compliant...)

I am slowly redesign the blog before adding new content, please feel free if you have any suggestion :)

**Comment by robinmetral** [comment]
Hi Sylvain, thanks for taking care of this!

I think it looks much better, now I'm noticing your side notes :slightly_smiling_face: It's okay too if everything is not 100% compliant to WCAG - but it's good to keep these guidelines in mind when designing!

I'll let you know if I have any other suggestions for your redesign!
