### ISSUE TITLE
Certificats wildcard avec Let’s Encrypt

### ISSUE THREAD

**Issue by nbenm** [sylvaindurand/sylvaindurand.org#20]
Salut,

C'est la seule doc qui ait fonctionné pour moi.
Merci.

**Comment by sylvaindurand** [comment]
De rien ! Je n'utilise plus de certificats wildcard donc je ne peux pas vérifier, mais soyez attentifs aux premiers renouvellements : je ne sais pas s'ils fonctionneront bien, il est possible que la méthode ait changée depuis.
