### ISSUE TITLE
Complément d'info sur votre tuto site multilingue Jekyll

### ISSUE THREAD

**Issue by pand4z** [sylvaindurand/sylvaindurand.org#3]
Bonjour,

J'ai suivi votre tuto sur comment rendre Jekyll multilingue, et d'ailleurs merci beaucoup pour cet article hyper intéressant.

Cependant, je n'arrive pas à savoir comment gérer la page d'accueil en multilingue qui se trouve forcément à la racine en multilingue... Il y'a surement quelque chose que je n'ai pas compris.

Pouvez vous m'aider à ce sujet ?

Merci bien par avance !

**Comment by pand4z** [comment]
En fait c'est bon, 

J'ai analysé ce que vous avez fait via la structure de votre site (surtout la page "journal" qui a donné la piste)... j'ai créé un index à la racine normal, ensuite créé une page index avec lang : fr et créé un sélecteur de langue (différent de celui qui va être affiché automatiquement dans les posts mais visuellement le même) qui va faire le nécessaire juste pour l'accueil pour vu que le reste tourne tout seul après....

C'est parce que je butais dessus en étant fatigué et puis comme ça va mieux maintenant après le repos c'est plus limpide.

En tout cas merci pour votre tuto hyper efficace ;)

**Comment by sylvaindurand** [comment]
Bonjour, je suis justement en train de mettre à jour le tutoriel ! (qui n'est pas si clair par endroit)
Le répertoire https://github.com/sylvaindurand/multilingual-jekyll montre un exemple d'adaptation sur le site par défaut de Jekyll. Regardez le dernier commit pour avoir un exemple. N'hésitez pas à m'envoyer un issue si besoin d'aide :)

**Comment by pand4z** [comment]
Merci ! Je vais regarder ça de plus près et comparer avec ce que j'ai fait du coup. J'attend votre nouveau tuto avec impatience ! :) 

Bonne continuation !

**Comment by sylvaindurand** [comment]
J'étais très motivé pour le faire le samedi matin qui suivait, mais l'actualité en a décidé autrement, et le sujet m'est sorti de la tête depuis... Promis, je n'oublie pas ! Néanmoins, il n'y aura rien de plus par rapport à ce qui est dans le répertoire "multilingual-jekyll" ;)

**Comment by pand4z** [comment]
ça marche, merci à toi pour cet effort  pour le tuto, j'ai réussi
finalement à tout mettre en multilingue sur mon jekyll principalement grâce
à ton tuto, j'avais juste fait une grosse confusion sur le config.yml et
les .yml à mettre dans le _data...

J'attend avec impatience ton tuto que je linkerais d'ailleurs sur mon blog
;) à bientôt et bon courage

--
Sam Rakoto
06.71.53.61.60

Le 4 janvier 2016 à 10:59, Sylvain Durand <notifications@github.com> a
écrit :

**Comment by sylvaindurand** [comment]
Le tutoriel a (enfin...) été réécrit.
Il comprenait un certain nombre d'erreurs qui, je l'espère, ont été corrigées. Il est aussi nettement plus flexible, permettant n'importe quelle organisation de fichiers, autant de langues que souhaitées...

N'hésite pas à me dire ce que tu en penses, et à me faire part de tes remarques !
