### ISSUE TITLE
Github Pages + jekyll 3

### ISSUE THREAD

**Issue by btcdrak** [sylvaindurand/sylvaindurand.org#4]
Just a heads up, it seems like the recent Github Pages upgrade to Jekyll 3 has broken this ML strategy. https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0

**Comment by sylvaindurand** [comment]
Ah ah!
I have been waiting a long time for Github to push Jekyll 3.0. Il will update my website and every article about Jekyll to make things work (and I'll update my multilanguage article, which waits for a long time).

What have you seen which may make my ML strategy not work in the future?

**Comment by btcdrak** [comment]
Well I solved the problem I was having with bitcoincore.org (source at github.com/bitcoin-core/website). It turns out the `_config.yml` trick doesnt work any more. There are a few other nasties, like `domain.com/some/url/` returns a 404 if your permalink is `/some/url` without the trailing slash.

I fixed this by adding `lang:` and `type:` directly to each page's front matter.

**Comment by landswellsong** [comment]
Subscribing to the thread in case I don't figure out a solution on my own faster.

**Comment by sylvaindurand** [comment]
I'm currently moving in another apartment,

**Comment by sylvaindurand** [comment]
Well, it seems that scope values doesn't work on subdirectories... 
It looks like a Jekyll 3.0.0+ bug, as scope values remains in the docs. 

A temporary workaround is use frontmatter in every file involved.

Please see this issue on Jekyll repo for further informations: https://github.com/jekyll/jekyll/issues/4458

**Comment by sylvaindurand** [comment]
I almost completely rewrite the tutorial Making multilingual Jekyll, in order to correct many errors. 

I drop the ‘file tree’ and ‘default scope’ system, as it doesn't work anymore. Anyway, the new method should be much more flexible. When default scope will work again, I'll mention it.

Don't hesitate to give me feedback about this tutorial; many mistakes and typos must remain!

**Comment by sylvaindurand** [comment]
As you can see, scope values should work correctly in Jekyll 3.0.4 and 3.1.3!
