### ISSUE TITLE
Améliorer la typographie sous Jekyll

### ISSUE THREAD

**Issue by robinmetral** [sylvaindurand/sylvaindurand.org#5]
Merci pour cet excellent article !

Une idée pour intégrer cette fonctionnalité avec Jekyll multilingue : 

 - mettre le code dans un fichier `_includes/typography.html`
 - dans `_layouts/default.html` : 
```
{% if page.lang != 'en' %}
    {% include typography.html %}
{% else %}
    {{ content }}
{% endif %}
```

Ça sautera l'include et accélérera le rendu d'une page en anglais (où la typo est déjà bonne), et le code du layout est plus propre :slightly_smiling_face: 

Ensuite si on veut ajouter des règles de typographies pour d'autres langues, on peut faire des boucles dans `typgraphy.html` !

**Comment by sylvaindurand** [comment]
_(six mois plus tard...)_

Tout à fait d'accord, j'utilise moi-même cette solution sur mon site personnel :)
J'ai rajouté une mention à la fin de l'article. Merci !

**Comment by robinmetral** [comment]
Super, merci pour l'ajout !
Bonne suite avec Jekyll et la JAMstack :slightly_smiling_face:
