### ISSUE TITLE
Setting up a Nginx web server on macOS

### ISSUE THREAD

**Issue by hackerunet** [sylvaindurand/sylvaindurand.org#6]
This configuration doesnt work for macos sierra, the port 80 can only be opened by a privileged user and if you change user youruser staff; on nginx config you get a 2018/10/17 11:28:01 [emerg] 5241#0: bind() to 0.0.0.0:80 failed (13: Permission denied)

so, what's the solution for this?

**Comment by sylvaindurand** [comment]
You won't be able to use port 80 without a privileged user. This is why you must use a sudo...
You can see [https://apple.stackexchange.com/questions/37418/how-can-i-open-port-80-so-a-non-root-process-can-bind-to-it](this page) to see why!
