### ISSUE TITLE
Question: multilingual in pages directories

### ISSUE THREAD

**Issue by pathetiq** [sylvaindurand/sylvaindurand.org#6]
Hi Sylvain,

I was reading your post to configure Jekyll to be multilingual and one thing I can't figure out is how to make it work for the static pages I have.

As an example if I have the following structure  in about/ and apropos/ how can jekyll know which directory to pull regarding the language?:
```
about:
a-propos-hackfest  code-ethique  collaborators  index.html  politique-confidentialite  the-crew  the-logos  wallpapers

about/a-propos-hackfest:
index.html

about/code-ethique:
index.html

about/collaborators:
index.html

about/politique-confidentialite:
index.html

about/the-crew:
index.html

about/the-logos:
index.html

about/wallpapers:
index.html
```

Thanks in advance for your time and let me know if you need more details.

**Comment by sylvaindurand** [comment]
Hi!

I almost completely rewrite the tutorial "Making multilingual Jekyll". I corrected many errors. Moreover, the new method should be much more flexible (as many languages as you want, no restrictions on the organization of files ...) and is compatible with Jekyll 3.0.

Let me know if that answers your question. I'd be happy to help you if necessary.

**Comment by pilarargudo** [comment]
Thank you so much for your post, it's really useful!

**Comment by sylvaindurand** [comment]
You're welcome!
