### ISSUE TITLE
I read your article about whitespace of…

### ISSUE THREAD

**Issue by Phlow** [sylvaindurand/sylvaindurand.org#7]
…liquid <https://www.sylvaindurand.org/compressing-liquid-generated-html/>

Do you know about the [compress layout](https://github.com/penibelst/jekyll-compress-html)? Minifies your html very handy :)

I like your article about typography :+1:

**Comment by sylvaindurand** [comment]
Wow, that's a great – and clever – method. I added a link in my article!

Thanks for your support!
