### ISSUE TITLE
Cartographie avec R

### ISSUE THREAD

**Issue by gmkey69** [sylvaindurand/sylvaindurand.org#7]
Bonjour Sylvain,
Je trouve votre article très bien fait et les résultats visuels semblent très intéressants mais j'ai beau suivre votre sript à la lettre (ou plutôt l'adapter aux données ADMIN EXPRESS), rien ne sort que ce soit dans la visualisation R Studio ou dans les PDF cibles.

Je précise que je n'ai aucun message d'erreur de R Studio... et que java est bien à jour.
Une idée de ce qui se passe ? 
Merci d'avance.

**Comment by sylvaindurand** [comment]
Hélas, cet article à 5 ans et les instructions pour le paramétrage sont peut-être datées... 
N'utilisant (à regret !) plus *R* en ce moment, et ne connaissant pas votre configuration, j'aurai hélas du mal à vous aider !
