### ISSUE TITLE
Merci

### ISSUE THREAD

**Issue by cbrocas** [sylvaindurand/sylvaindurand.org#8]
Ce n'est pas un problème, juste un retour. Merci pour l'article sur Jekyll multilingues, utilisé cette nuit pour traduire : https://sec2016.rmll.info/. 
Super utile ! 
J'avais produit à l'automne le site uniquement en anglais car je n'avais pas trouvé d'article expliquant aussi bien cette méthode de traduction  ne requérant *aucun* plugin.
Thanks/merci !

**Comment by sylvaindurand** [comment]
Tout le plaisir est pour moi, très heureux que cela puisse être utile aux bonnes causes !
