### ISSUE TITLE
Beautifully designed!

### ISSUE THREAD

**Issue by harfangk** [sylvaindurand/sylvaindurand.org#9]
Greetings!

I came across your blog while I was looking for ways to make a multilingual Jekyll blog. And I'd like to thank you for creating this beautiful design! Your blog is a pure pleasure to read. The minimalist design is great, but your typography is just marvelous. After rummaging through so many websites with terrible typography that literally hurt my eyes, it was a welcome respite to read your blog. I like Medium's style, but I think yours is even better - I almost wish your text style was something of a web standard. 

I was about to fork your github page to customize it for my own blog when I noticed the license part in your about page, which said 

> The source code is freely available on GitHub. The design isn’t reusable; however, other content and codes presented on this website published under the MIT license.

So before proceeding with my customization, I wanted ask you whether I'm allowed to fork and customize your site's layout and styling!

And regardless of whether you allow it or not, I want to thank you again for creating this pleasant blog. Cheers!

**Comment by sylvaindurand** [comment]
Hello! Thank you very much for your very nice words. I tried to make a website I liked, and I spent quite much time into it!
You may use its code and typography. However, I believe it's "dark header" with the Turgot Paris map is its identity and I would prefer other people to find different decoration :)

Anyway, I'm thinking to remove its code from GitHub, as Google references it way too much (sometimes before the real website...) and the code of multilingual-jekyll is sufficient for most users.

**Comment by harfangk** [comment]
Thank you for allowing its use! I will try to make good use of the typography :D
